### ISSUE TITLE
(edit 'sym ..) does't work

### ISSUE THREAD

**Issue by vsov** [iprog4u/docker-tinycore-picolisp#1]
`(edit 'sym ..)` doesn't work because there's no vim installed in the minimal image. `(call "vim"` ...  is hardcoded in `/usr/lib/picolisp/lib/edit.l`, and vim is required for proper navigation through nested data structures, would it be possible to add vim to minimal image?

**Comment by iprog4u** [comment]
Certainly!  That's some much needed basic functionality. I'll upload a new
version including vim and vip (a vi clone written in PicoLisp by Alexander
Burger) tonight.

**Comment by iprog4u** [comment]
I've added vim to the container and tested that it works however building the image from a Dockerfile is still proving to be a fight.  I'll look into this over the weekend and as a bonus try to get vip working as well.

**Comment by vsov** [comment]
Thanks a lot!

**Comment by iprog4u** [comment]
After trying to include vim in various ways I've determined that it adds far too much bulk to the image and isn't worth the bloat.  Instead I recommend using vim to edit files and share them with your container with the -v option to docker.  Then you can (load "/path/to/shared/folder/with-v-option/my-source-file.l") from within the container.  This allows you to treat the container as ephemeral as well as keeping the docker image size at 14MB rather than 100+ MB (because of the way Docker tracks everything that's done in a container).

If there's a better way to include vim I'd be happy to but everything tried so far won't work within the context of a Dockerfile build.  For windows I know that MinGW and Cygwin are fast ways to get vim.  For OSX and Linux it should be even easier.  Hope this helps.  Thanks for trying my container and let me know if there's a clean way to get Docker to build the image.

**Comment by iprog4u** [comment]
There may be a way to use buildroot to compile a very minimal, custom linux container with only vim and picoLisp installed.  I haven't been able to get it to work yet but only have tried once so far with different goals in mind so again, it may be possible.  For now I recommend editing in your main working environment and sharing files with the container using the '-v' option to docker until I can get buildroot and Docker to play nicely together.

**Comment by iprog4u** [comment]
Fixed by building a custom 64-Bit container with Vim and zsh (because why not at that point) to yield a ~46MB image.

Please use the new container and instructions found at:
[https://hub.docker.com/r/progit/pil-minimal/](https://hub.docker.com/r/progit/pil-minimal/)

Essentially:
```docker pull progit/pil-minimal```
```docker run -it --rm progit/pil-minimal pil +```
... and you'll be immediately dropped into the REPL.

To access to the shell:

```docker run -it --rm progit/pil-minimal /bin/zsh```
(or sh if you prefer for some reason)

Enjoy and let me know how it works for you.
